apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: echo
        image: jmalloc/echo-server:0.1.0
      - name: envoy
        image: envoyproxy/envoy:v1.14.1
        args:
        - -c
        - /etc/envoy/config.yaml
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
        - name: envoy-config
          mountPath: /etc/envoy
          readOnly: false
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
      - name: envoy-config
        configMap:
          name: envoy
