apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: proxy
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: proxy
