apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
  namespace: cert-gen
  labels:
    app: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      serviceAccountName: generator
      containers:
      - name: spire-agent
        image: gcr.io/spiffe-io/spire-agent:0.10.0
        command: ["sleep"]
        args: ["1000000"]
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: false
        - name: certs
          mountPath: /tmp/certs
          readOnly: false
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
      - name: certs
        emptyDir:
          medium: Memory
